# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  workflow_dispatch:
env:
   SONAR_CLOUD: ${{ secrets.SONAR_CLOUD }}
   SONAR_ORG: ${{ secrets.SONAR_ORG }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn clean install

    - name: Package
      run: mvn package

    - name: Unit Test
      run: mvn test

    - name: List current directory
      run: ls -la

    - name: target folder content
      run: |
        cd target
        ls -la

    - name: build & SonarQube analysis
      run: |
        mvn verify sonar:sonar -Dsonar.organization=${{ secrets.SONAR_ORG }} -Dsonar.projectKey=demo-testrepo -Dsonar.login=${{ secrets.SONAR_CLOUD }} -Dsonar.sources=src/main/ -Dsonar.tests=src -Dsonar.exclusions=src/main/java/** -Dsonar.test.exclusions=src/main/java/** -Dsonar.host.url=https://sonarcloud.io
